encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
pygments: true

# 作者信息
author: 
  name: Poplar
  email: atfeng2011@qq.com
  link: http://w-poplar.github.io/
  weibo: http://weibo.com/u/1640376507
  github: https://github.com/w-poplar
  github_username:  w-poplar
  weibo_username:  somanywf

# 站点信息
title : 聚木成林
description: 
  码农待开发...
url: http://w-poplar.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 当任何时候觉得累<br>你的大脑就在进化<br> 当任何时候觉得轻松<br>你都在使用你的习惯<br>

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章